name: Release Doc
on:
  workflow_dispatch:
    inputs:
        command:
          description: 'Command for manual trigger'
          required: true
          default: 'release_doc' 

jobs:
   build:
       runs-on: ubuntu-latest
          
       steps:
          - name: Checkout code
            uses: actions/checkout@v2
          
          - name: Run your build steps
            run: echo "triggered by gh cli command ${{ github.event.inputs.command }}"
          